steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-b643a19bd114/my-repository/sample-app:v2.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-b643a19bd114/my-repository/sample-app:v2.0']
images:
- 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-b643a19bd114/my-repository/sample-app:v2.0'
options:
  logging: CLOUD_LOGGING_ONLY
